2025-07-04 01:33:53,763 - clemcore.cli - INFO - Transcribing game interactions that match game_selector=all
2025-07-04 01:33:53,763 - clemcore.cli - INFO - Transcribing game interactions that match game_selector=all
2025-07-04 01:33:53,770 - clemcore.run - INFO - Found 253 interaction files to transcribe. Games: all
2025-07-04 01:33:53,978 - clemcore.cli - INFO - Building transcripts took 0:00:00.215335
2025-07-04 01:45:49,086 - clemcore.cli - INFO - Transcribing game interactions that match game_selector=all
2025-07-04 01:45:49,086 - clemcore.cli - INFO - Transcribing game interactions that match game_selector=all
2025-07-04 01:45:49,086 - clemcore.run - INFO - Found 2 interaction files to transcribe. Games: all
2025-07-04 01:45:49,093 - clemcore.cli - INFO - Building transcripts took 0:00:00.007184
2025-07-04 03:19:16,750 - clemcore.cli - INFO - Transcribing game interactions that match game_selector=all
2025-07-04 03:19:16,750 - clemcore.cli - INFO - Transcribing game interactions that match game_selector=all
2025-07-04 03:19:16,751 - clemcore.run - INFO - Found 12 interaction files to transcribe. Games: all
2025-07-04 03:19:16,764 - clemcore.cli - INFO - Building transcripts took 0:00:00.013209
2025-07-04 06:38:11,444 - clemcore.cli - INFO - Transcribing game interactions that match game_selector=all
2025-07-04 06:38:11,444 - clemcore.cli - INFO - Transcribing game interactions that match game_selector=all
2025-07-04 06:38:11,447 - clemcore.run - INFO - Found 120 interaction files to transcribe. Games: all
2025-07-04 06:38:11,522 - clemcore.cli - INFO - Building transcripts took 0:00:00.078284
2025-07-19 20:21:33,000 - clemcore.cli - ERROR - No games found matching the game selector='escape_room'.
Traceback (most recent call last):
  File "/Users/kushalkoshti/WORK/CLEM/mapworld-thesis/.venv/lib/python3.10/site-packages/clemcore/cli.py", line 152, in run
    game_specs = game_registry.get_game_specs_that_unify_with(game_selector)  # throws error when nothing unifies
  File "/Users/kushalkoshti/WORK/CLEM/mapworld-thesis/.venv/lib/python3.10/site-packages/clemcore/clemgame/registry.py", line 326, in get_game_specs_that_unify_with
    raise ValueError(f"No games found matching the game selector='{game_selector}'.")
ValueError: No games found matching the game selector='escape_room'.
2025-07-19 20:21:33,001 - clemcore.cli - ERROR - No games found matching the game selector='escape_room'.
Traceback (most recent call last):
  File "/Users/kushalkoshti/WORK/CLEM/mapworld-thesis/.venv/lib/python3.10/site-packages/clemcore/cli.py", line 152, in run
    game_specs = game_registry.get_game_specs_that_unify_with(game_selector)  # throws error when nothing unifies
  File "/Users/kushalkoshti/WORK/CLEM/mapworld-thesis/.venv/lib/python3.10/site-packages/clemcore/clemgame/registry.py", line 326, in get_game_specs_that_unify_with
    raise ValueError(f"No games found matching the game selector='{game_selector}'.")
ValueError: No games found matching the game selector='escape_room'.
